// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1_r0N21hGmQZiYXOkDFQRkJdDxRMQyQA',
    appId: '1:846522666048:android:a50ee92b04522d4cd0a3a5',
    messagingSenderId: '846522666048',
    projectId: 'project-habit-tracker',
    storageBucket: 'project-habit-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuZ5pcx7qPHmbjDv0vwVc2blkZVgwwmF4',
    appId: '1:846522666048:ios:39fc63a60a0cfd4ad0a3a5',
    messagingSenderId: '846522666048',
    projectId: 'project-habit-tracker',
    storageBucket: 'project-habit-tracker.appspot.com',
    iosClientId: '846522666048-r6s6q3dt9m99l8ung7cbq7lsv022o4qi.apps.googleusercontent.com',
    iosBundleId: 'com.project2.app',
  );
}
